[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://pixelmagnet-mongodb-client.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
[[redirects]]
  from = "/api/*"
  to = "http://localhost:3002/:splat" # замініть на локальний порт вашого сервера
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
