[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://pixelmagnet-mongodb-client.netlify.app"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, DELETE"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
